os:
  - linux

sudo: required

services:
  - docker

language: go

go:
  - 1.11.x

script:
  - go get github.com/mritd/gcrsync
  - gcrsync --querylimit 20 --processlimit 10 --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --githubtoken ${GITHUB_TOKEN}
